//
// LevelExpandSchemaDoc.cs
//
// This file was generated by XMLSpy 2005 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//


using System;

namespace UFIDA.U8.UAP.Services.ReportElements
{
	public class LevelExpandSchemaDoc : Altova.Xml.Document
	{
		override protected void DeclareNamespaces(Altova.Xml.Node node)
		{
		}
	}
}
