//
// ReportLevelExpandType.cs.cs
//
// This file was generated by XMLSpy 2005 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//


using System;
using System.Collections;
using System.Xml;
using UFIDA.U8.UAP.Services.ReportElements.Altova.Types;

namespace UFIDA.U8.UAP.Services.ReportElements
{
	public class ReportLevelExpandType : Altova.Xml.Node
	{
		#region Forward constructors
		public ReportLevelExpandType() : base() { SetCollectionParents(); }
		public ReportLevelExpandType(XmlDocument doc) : base(doc) { SetCollectionParents(); }
		public ReportLevelExpandType(XmlNode node) : base(node) { SetCollectionParents(); }
		public ReportLevelExpandType(Altova.Xml.Node node) : base(node) { SetCollectionParents(); }
		#endregion // Forward constructors

		public override void AdjustPrefix()
		{

			for (int i = 0; i < DomChildCount(NodeType.Attribute, "", "Name"); i++)
			{
				XmlNode DOMNode = GetDomChildAt(NodeType.Attribute, "", "Name", i);
				InternalAdjustPrefix(DOMNode, false);
			}

			for (int i = 0; i < DomChildCount(NodeType.Attribute, "", "IsDefault"); i++)
			{
				XmlNode DOMNode = GetDomChildAt(NodeType.Attribute, "", "IsDefault", i);
				InternalAdjustPrefix(DOMNode, false);
			}

			for (int i = 0; i < DomChildCount(NodeType.Element, "", "LevelExpandItem"); i++)
			{
				XmlNode DOMNode = GetDomChildAt(NodeType.Element, "", "LevelExpandItem", i);
				InternalAdjustPrefix(DOMNode, true);
				new LevelExpandItemType(DOMNode).AdjustPrefix();
			}
		}


		#region Name accessor methods
		public int GetNameMinCount()
		{
			return 0;
		}

		public int NameMinCount
		{
			get
			{
				return 0;
			}
		}

		public int GetNameMaxCount()
		{
			return 1;
		}

		public int NameMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetNameCount()
		{
			return DomChildCount(NodeType.Attribute, "", "Name");
		}

		public int NameCount
		{
			get
			{
				return DomChildCount(NodeType.Attribute, "", "Name");
			}
		}

		public bool HasName()
		{
			return HasDomChild(NodeType.Attribute, "", "Name");
		}

		public SchemaString GetNameAt(int index)
		{
			return new SchemaString(GetDomNodeValue(GetDomChildAt(NodeType.Attribute, "", "Name", index)));
		}

		public XmlNode GetStartingNameCursor()
		{
			return GetDomFirstChild( NodeType.Attribute, "", "Name" );
		}

		public XmlNode GetAdvancedNameCursor( XmlNode curNode )
		{
			return GetDomNextChild( NodeType.Attribute, "", "Name", curNode );
		}

		public SchemaString GetNameValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.Xml.XmlException("Out of range");
			else
				return new SchemaString( curNode.Value );
		}


		public SchemaString GetName()
		{
			return GetNameAt(0);
		}

		public SchemaString Name
		{
			get
			{
				return GetNameAt(0);
			}
		}

		public void RemoveNameAt(int index)
		{
			RemoveDomChildAt(NodeType.Attribute, "", "Name", index);
		}

		public void RemoveName()
		{
			while (HasName())
				RemoveNameAt(0);
		}

		public void AddName(SchemaString newValue)
		{
			AppendDomChild(NodeType.Attribute, "", "Name", newValue.ToString());
		}

		public void InsertNameAt(SchemaString newValue, int index)
		{
			InsertDomChildAt(NodeType.Attribute, "", "Name", index, newValue.ToString());
		}

		public void ReplaceNameAt(SchemaString newValue, int index)
		{
			ReplaceDomChildAt(NodeType.Attribute, "", "Name", index, newValue.ToString());
		}
		#endregion // Name accessor methods

		#region Name collection
        public NameCollection	MyNames = new NameCollection( );

        public class NameCollection: IEnumerable
        {
            ReportLevelExpandType parent;
            public ReportLevelExpandType Parent
			{
				set
				{
					parent = value;
				}
			}
			public NameEnumerator GetEnumerator() 
			{
				return new NameEnumerator(parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return GetEnumerator();
			}
        }

        public class NameEnumerator: IEnumerator 
        {
			int nIndex;
			ReportLevelExpandType parent;
			public NameEnumerator(ReportLevelExpandType par) 
			{
				parent = par;
				nIndex = -1;
			}
			public void Reset() 
			{
				nIndex = -1;
			}
			public bool MoveNext() 
			{
				nIndex++;
				return(nIndex < parent.NameCount );
			}
			public SchemaString  Current 
			{
				get 
				{
					return(parent.GetNameAt(nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(Current);
				}
			}
    	}

        #endregion // Name collection

		#region IsDefault accessor methods
		public int GetIsDefaultMinCount()
		{
			return 0;
		}

		public int IsDefaultMinCount
		{
			get
			{
				return 0;
			}
		}

		public int GetIsDefaultMaxCount()
		{
			return 1;
		}

		public int IsDefaultMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetIsDefaultCount()
		{
			return DomChildCount(NodeType.Attribute, "", "IsDefault");
		}

		public int IsDefaultCount
		{
			get
			{
				return DomChildCount(NodeType.Attribute, "", "IsDefault");
			}
		}

		public bool HasIsDefault()
		{
			return HasDomChild(NodeType.Attribute, "", "IsDefault");
		}

		public SchemaBoolean GetIsDefaultAt(int index)
		{
			return new SchemaBoolean(GetDomNodeValue(GetDomChildAt(NodeType.Attribute, "", "IsDefault", index)));
		}

		public XmlNode GetStartingIsDefaultCursor()
		{
			return GetDomFirstChild( NodeType.Attribute, "", "IsDefault" );
		}

		public XmlNode GetAdvancedIsDefaultCursor( XmlNode curNode )
		{
			return GetDomNextChild( NodeType.Attribute, "", "IsDefault", curNode );
		}

		public SchemaBoolean GetIsDefaultValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.Xml.XmlException("Out of range");
			else
				return new SchemaBoolean( curNode.Value );
		}


		public SchemaBoolean GetIsDefault()
		{
			return GetIsDefaultAt(0);
		}

		public SchemaBoolean IsDefault
		{
			get
			{
				return GetIsDefaultAt(0);
			}
		}

		public void RemoveIsDefaultAt(int index)
		{
			RemoveDomChildAt(NodeType.Attribute, "", "IsDefault", index);
		}

		public void RemoveIsDefault()
		{
			while (HasIsDefault())
				RemoveIsDefaultAt(0);
		}

		public void AddIsDefault(SchemaBoolean newValue)
		{
			AppendDomChild(NodeType.Attribute, "", "IsDefault", newValue.ToString());
		}

		public void InsertIsDefaultAt(SchemaBoolean newValue, int index)
		{
			InsertDomChildAt(NodeType.Attribute, "", "IsDefault", index, newValue.ToString());
		}

		public void ReplaceIsDefaultAt(SchemaBoolean newValue, int index)
		{
			ReplaceDomChildAt(NodeType.Attribute, "", "IsDefault", index, newValue.ToString());
		}
		#endregion // IsDefault accessor methods

		#region IsDefault collection
        public IsDefaultCollection	MyIsDefaults = new IsDefaultCollection( );

        public class IsDefaultCollection: IEnumerable
        {
            ReportLevelExpandType parent;
            public ReportLevelExpandType Parent
			{
				set
				{
					parent = value;
				}
			}
			public IsDefaultEnumerator GetEnumerator() 
			{
				return new IsDefaultEnumerator(parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return GetEnumerator();
			}
        }

        public class IsDefaultEnumerator: IEnumerator 
        {
			int nIndex;
			ReportLevelExpandType parent;
			public IsDefaultEnumerator(ReportLevelExpandType par) 
			{
				parent = par;
				nIndex = -1;
			}
			public void Reset() 
			{
				nIndex = -1;
			}
			public bool MoveNext() 
			{
				nIndex++;
				return(nIndex < parent.IsDefaultCount );
			}
			public SchemaBoolean  Current 
			{
				get 
				{
					return(parent.GetIsDefaultAt(nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(Current);
				}
			}
    	}

        #endregion // IsDefault collection

		#region LevelExpandItem accessor methods
		public int GetLevelExpandItemMinCount()
		{
			return 1;
		}

		public int LevelExpandItemMinCount
		{
			get
			{
				return 1;
			}
		}

		public int GetLevelExpandItemMaxCount()
		{
			return 1;
		}

		public int LevelExpandItemMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetLevelExpandItemCount()
		{
			return DomChildCount(NodeType.Element, "", "LevelExpandItem");
		}

		public int LevelExpandItemCount
		{
			get
			{
				return DomChildCount(NodeType.Element, "", "LevelExpandItem");
			}
		}

		public bool HasLevelExpandItem()
		{
			return HasDomChild(NodeType.Element, "", "LevelExpandItem");
		}

		public LevelExpandItemType GetLevelExpandItemAt(int index)
		{
			return new LevelExpandItemType(GetDomChildAt(NodeType.Element, "", "LevelExpandItem", index));
		}

		public XmlNode GetStartingLevelExpandItemCursor()
		{
			return GetDomFirstChild( NodeType.Element, "", "LevelExpandItem" );
		}

		public XmlNode GetAdvancedLevelExpandItemCursor( XmlNode curNode )
		{
			return GetDomNextChild( NodeType.Element, "", "LevelExpandItem", curNode );
		}

		public LevelExpandItemType GetLevelExpandItemValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.Xml.XmlException("Out of range");
			else
				return new LevelExpandItemType( curNode );
		}


		public LevelExpandItemType GetLevelExpandItem()
		{
			return GetLevelExpandItemAt(0);
		}

		public LevelExpandItemType LevelExpandItem
		{
			get
			{
				return GetLevelExpandItemAt(0);
			}
		}

		public void RemoveLevelExpandItemAt(int index)
		{
			RemoveDomChildAt(NodeType.Element, "", "LevelExpandItem", index);
		}

		public void RemoveLevelExpandItem()
		{
			while (HasLevelExpandItem())
				RemoveLevelExpandItemAt(0);
		}

		public void AddLevelExpandItem(LevelExpandItemType newValue)
		{
			AppendDomElement("", "LevelExpandItem", newValue);
		}

		public void InsertLevelExpandItemAt(LevelExpandItemType newValue, int index)
		{
			InsertDomElementAt("", "LevelExpandItem", index, newValue);
		}

		public void ReplaceLevelExpandItemAt(LevelExpandItemType newValue, int index)
		{
			ReplaceDomElementAt("", "LevelExpandItem", index, newValue);
		}
		#endregion // LevelExpandItem accessor methods

		#region LevelExpandItem collection
        public LevelExpandItemCollection	MyLevelExpandItems = new LevelExpandItemCollection( );

        public class LevelExpandItemCollection: IEnumerable
        {
            ReportLevelExpandType parent;
            public ReportLevelExpandType Parent
			{
				set
				{
					parent = value;
				}
			}
			public LevelExpandItemEnumerator GetEnumerator() 
			{
				return new LevelExpandItemEnumerator(parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return GetEnumerator();
			}
        }

        public class LevelExpandItemEnumerator: IEnumerator 
        {
			int nIndex;
			ReportLevelExpandType parent;
			public LevelExpandItemEnumerator(ReportLevelExpandType par) 
			{
				parent = par;
				nIndex = -1;
			}
			public void Reset() 
			{
				nIndex = -1;
			}
			public bool MoveNext() 
			{
				nIndex++;
				return(nIndex < parent.LevelExpandItemCount );
			}
			public LevelExpandItemType  Current 
			{
				get 
				{
					return(parent.GetLevelExpandItemAt(nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(Current);
				}
			}
    	}

        #endregion // LevelExpandItem collection

        private void SetCollectionParents()
        {
            MyNames.Parent = this; 
            MyIsDefaults.Parent = this; 
            MyLevelExpandItems.Parent = this; 
	}
}
}
